# Generated by Django 4.1.7 on 2023-03-12 05:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_alter_inventorymodel_name_alter_inventorymodel_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', related_query_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='products_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, null=True), size=None),
        ),
    ]
