# Generated by Django 4.1.7 on 2023-03-12 05:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorymodel_name_alter_inventorymodel_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymodel',
            name='products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='products_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, null=True), null=True, size=None),
        ),
    ]
